### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by jerrygreen** [mimiMonads/vixeny#3]
If project is called Vixeny, why repo name «functor»?

Harder to find in Google if heard elsewhere btw.

**Comment by mimiMonads** [comment]
The original name was 'functor,' which later changed to 'endorfunctor' and ultimately became 'Vixeny.' We are currently in the alpha stage, and I will request the Deno project to remove the last two names to maintain consistency between the names, in Deno and in npm(with the right name)

There's a lot to do but please tell me if you have any other recommendation

**Comment by mimiMonads** [comment]
I already changed the name and docs~ thanks
