### ISSUE TITLE
Plugin API re-design

### ISSUE THREAD

**Issue by aquapi** [mimiMonads/vixeny#32]
As Vix uses dynamic code generation for optimizing request handling, it would be great to fully leverage that with an API that allows developers to directly inject code into the control flow.

This can be used to optimize things such as request validation since it can inline code directly into the handler.

**Comment by mimiMonads** [comment]
@emastho 

Let's start with this, I think that one of the biggest problems with plugging is the way that we have to unwrap the plugin:

```ts
const hello  = plugin.type({
  name: Symbol.for("Unique Identifier"),
  type: "string",
  f: () => () => () => "hello world",
})

const serve = wrap({
  cyclePlugin:{
    hello
  }
})()
  .stdPetition({
    path: "/",
    f: ctx => ctx.hello
  })
  .testRequests()

await serve(
  new Request('http://localhost/')
).then(r => r.text())
  .then( console.log)
```

Where `f` is curried and that could be bothersome for some programmers

**Comment by mimiMonads** [comment]
#49
