### ISSUE TITLE
consider using `"bun"` package.json exports condition

### ISSUE THREAD

**Issue by Jarred-Sumner** [mimiMonads/vixeny#4]
Using a [package.json `"exports"`](https://nodejs.org/api/packages.html#conditional-exports) condition would let you `import vixeny from 'vixeny'`
```js
// Instead of
import vixeny from "vixeny/fun";
```

```js
// they can do
import vixeny from "vixeny";
```

**Comment by mimiMonads** [comment]
thank! I already push the change, and it should be ready for the next release
