### ISSUE TITLE
Bun macros could make your life easier?

### ISSUE THREAD

**Issue by icetbr** [mimiMonads/vixeny#6]
Hi there, I'm not sure but I think this might be a game changer for AOT ("compiled") code.

You don't need to use string concat / eval anymore.

https://bun.sh/blog/bun-macros

**Comment by mimiMonads** [comment]
Hello,

Thank you for bringing up an intriguing point about AOT (Ahead-of-Time) compiled code and its potential transformation. I wanted to provide some insight into my current work involving both "Deno" and "Bun."

Currently, I'm utilizing common code for both platforms, including some exclusive optimizations specific to "Bun." However, these still require rigorous testing.

My main concentration has been on the development of the website and the related documentation. While I recognize the need to separate the "Deno" and "Bun" code, I haven't had the opportunity to do so just yet. Rest assured, this is on my agenda, and I plan to undertake it after the release of v0.1.

Thank you once again for your thoughtful question, and please don't hesitate to reach out if you have any further inquiries or insights.

**Comment by icetbr** [comment]
Oh, Deno doesn't have macro. That's the thing about runtime exclusive features. Keep up your good work, I like your functional code style, yours might be the first non Rxjs server framework I've seen.

**Comment by mimiMonads** [comment]
Thank you very much and let me know if you have any question, there's much to do, but I'm motivated
